### ISSUE TITLE
Helm support

### ISSUE THREAD

**Issue by embcla** [easimon/tado-exporter#12]
Hi there

I'm really interested in your project, for personal reasons of course: logging temperature!
Have you investigated making a helm chart of this? 

When I tried building the docker image, it was pulling all sorts of devel packages.
Would it be possible to make a smaller binary image?

Thanks for keeping it open!

**Comment by easimon** [comment]
Providing a helm chart would IMHO be overkill. I could add a k8s deployment manifest as an example though. 

The resulting docker image is around 160 MB, most of which is the JRE base image. The reason why it pulls a lot of dev packages during build, is, because the complete build uses docker, and executes all tests in docker as well. So it needs a JDK, Maven and all test dependencies during build. 

But since it is a multi stage build, these are not included in the final image, which contains only a JRE and the shaded app jar. The only way to shrink this would be to create a GraalVM native image instead -- which I might do at some point.

**Comment by easimon** [comment]
GraalVM build tracked in #14 for now
